apiVersion: v1
kind: Service
metadata:
  name: yaya
spec:
  selector:
    app: yaya
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 4000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yaya
spec:
  selector:
    matchLabels:
      app: yaya
  replicas: 2
  template:
    metadata:
      labels:
        app: yaya
    spec:
      containers:
      - name: yaya
        image: 597647611698.dkr.ecr.us-east-1.amazonaws.com/devopsthehardway-ecr:latest
        ports:
        - containerPort: 4000